#!/usr/bin/env bash

PROGRAM_CLASS_PATH=${1}
MAIN_CLASS=${2}
ARG0=${3}
ARG1=${4}
ARG2=${5}
ARG3=${6}
ARG4=${7}
ARG5=${8}
IDTA_OUTPUT_FILE=data.ser
OUTPUT_DIR=data

rm -rf $IDTA_OUTPUT_FILE
rm -rf $OUTPUT_DIR
mkdir $OUTPUT_DIR
(/usr/bin/time -p java -Xmx12g -Xms12g -cp $PROGRAM_CLASS_PATH $MAIN_CLASS $ARG0 $ARG1 $ARG2 $ARG3 $ARG4 $ARG5) 2>$IDTA_OUTPUT_FILE
